/*======================================================================================================================================================
  MAGNITUDE ANALYSIS
  ======================================================================================================================================================*/

  -- FIND TOTAL CUSTOMERS BY COUNTRIES
SELECT 
country, 
COUNT(customer_key) AS customers
FROM gold_dim_customers
GROUP BY country
ORDER BY 2 DESC;
  
  -- FIND TOTAL CUSTOMERS BY GENDER
SELECT 
gender, 
COUNT(customer_key) AS customers 
FROM gold_dim_customers
GROUP BY gender
ORDER BY 2 DESC;
  
  -- FIND TOTAL PRODUCTS BY CATEGORY
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold_dim_products
GROUP BY category
ORDER BY 2 DESC;  
  
  -- WHAT IS THE AVERAGE COST IN EACH CATEGORY
SELECT 
category,
ROUND(AVG(cost),2) AS avg_cost
FROM gold_dim_products
GROUP BY category
ORDER BY 2 DESC;
  
  -- WHAT IS THE TOTAL REVENUE GENERATED BY EACH CATEGORY
SELECT 
p.category,
SUM(f.sales_amount) AS total_sales
FROM gold_fact_sales f  
RIGHT JOIN gold_dim_products p 
ON f.product_key=p.product_key  
GROUP BY category
ORDER BY 2 DESC;  

  --  FIND TOTAL REVENUE GENERATED BY EACH CUSTOMERS
SELECT 
c.customer_key,
CONCAT(c.first_name,' ',c.last_name) AS customer_name,
SUM(f.sales_amount) AS revenue
FROM gold_fact_sales f
LEFT JOIN  gold_dim_customers c
ON f.customer_key=c.customer_key
GROUP BY customer_key,customer_name
ORDER BY revenue DESC;  
  
  
  -- WHAT IS THE DISTRIBUTION OF THE SOLD ITEMS ACCROSS THE COUNTRIES
SELECT 
c.country,
SUM(f.quantity) AS total_quantity
FROM gold_dim_customers c
JOIN gold_fact_sales f
ON c.customer_key=f.customer_key
GROUP BY country
ORDER BY 2 DESC ;
  
  
  

  
  select product_name , category from gold_dim_products
  where category='';
  
  
  
  start transaction;
  update gold_dim_products
  set category='Components'
  where category='';
  rollback;